### ISSUE TITLE
Unable to initialize Sui client

### ISSUE THREAD

**Issue by hoanghun** [GrapeBaBa/sui4j#71]
I am unable to initialize Sui client with this fragment of code:
```
    val TEST_KEY_STORE_PATH = System.getProperty("user.home") + "/.sui/sui_config/sui.keystore"
    val sui = Sui("https://fullnode.devnet.sui.io:443", TEST_KEY_STORE_PATH)
```

This is the stack trace of the exception I am getting:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 65 out of bounds for byte[33]
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.bouncycastle.crypto.params.Ed25519PrivateKeyParameters.<init>(Unknown Source)
	at io.sui.crypto.ED25519KeyPair.decodeBase64(ED25519KeyPair.java:95)
	at io.sui.crypto.SuiKeyPair.decodeBase64(SuiKeyPair.java:103)
	at io.sui.crypto.FileBasedKeyStore.lambda$new$0(FileBasedKeyStore.java:52)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.sui.crypto.FileBasedKeyStore.<init>(FileBasedKeyStore.java:48)
	at io.sui.Sui.<init>(Sui.java:86)
```

Any ideas what is going on?

**Comment by hoanghun** [comment]
Seems like I generated a wrong keystore.

**Comment by GrapeBaBa** [comment]
> Seems like I generated a wrong keystore.

1. which sui version do you use?
2. Does your .keystore file works with official sui client?

**Comment by hoanghun** [comment]
ad 2. No, there was some breaking change in the keystore format I think.

**Comment by GrapeBaBa** [comment]
> ad 2. No, there was some breaking change in the keystore format I think.

Yes ,that is possible, since I got Covid-19 last month the java sdk development paused a while.
